version: "3"
services:  # this is where we list the images we'll be using and their configuration

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
        GRID_MAX_SESSION: 16
        GRID_BROWSER_TIMEOUT: 300
        GRID_TIMEOUT: 300

  chrome:
    image: selenium/node-chrome
    container_name: selenium-chrome
    depends_on:
      - selenium-hub # it will wait until that container is fully up and operational before linking to it
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444 # we'll use this later to connect to the grid
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2